baseURL ="https://tojans.me/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Tom's ramblings"
theme = "anatole"
summarylength = 20
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs"

# Enable Disqus
disqusShortname = "tojansramblings"

# Google Analytics
googleAnalytics = "UA-41936060-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Tom's ramblings"
author="Tom Janssens"
#copyright = "2020-2021"
description="Random opinionated blurbs"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# display mode dark or light
#displayMode = "dark"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/tojans"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/tomjanssens"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://www.github.com/tojans"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:tom@corebvba.be"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "RSS"
url = "/index.xml"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

[[menu.main]]
name = "Blog posts"
weight = 300
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "About"
weight = 350
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Contact"
weight = 400
identifier = "contact"
url = "/contact/"
